### PR TITLE
OMID-197 Replace Mockito timeout#never() with times(0)(Rajeshbabu)

### PR DESCRIPTION
**Pull request by chrajeshbabu**

### CODE REVIEW

**Review by stoty — APPROVED** [review]

**Review by virajjasani — APPROVED** [review]

**Comment by stoty** [comment]
Come to think of it, we may update mockito as well.

**Comment by chrajeshbabu** [comment]
> Come to think of it, we may update mockito as well.

we can rebase to 1.10.9 Istvan. Will make the changes.

**Comment by chrajeshbabu** [comment]
The test failures are not related to it.

**Comment by chrajeshbabu** [comment]
Pushed to master. Thanks for review @stoty @virajjasani .

**Pull request closed without merging**
