### PR TITLE
OMID-254 Upgrade to phoenix-thirdparty 2.1.0

### PR DESCRIPTION
**Pull request by NihalJain**

### CODE REVIEW

**Comment by NihalJain** [comment]
Built code locally and ran tests.:
```
mvn clean install -Dhbase.version=2.5.6-hadoop3 -DskipTests
mvn verify -Dsurefire.rerunFailingTestsCount=5 -Dhbase.version=2.5.6-hadoop3
```
FYI @chrajeshbabu , @stoty , @gjacoby126

**Comment by chrajeshbabu** [comment]
+lgtm

**Review by chrajeshbabu — APPROVED** [review]

**Review by stoty — APPROVED** [review]
+1 LGTM

**Comment by stoty** [comment]
Have you run the full Phoenix test suite with both Phoenix and Omid built with the new thirdparty, @NihalJain  ?

**Comment by NihalJain** [comment]
> Have you run the full Phoenix test suite with both Phoenix and Omid built with the new thirdparty,@NihalJain ?

Hi @stoty I have ran following for omid.

> Built code locally and ran tests.:
> 
> ```
> mvn clean install -Dhbase.version=2.5.6-hadoop3 -DskipTests
> mvn verify -Dsurefire.rerunFailingTestsCount=5 -Dhbase.version=2.5.6-hadoop3
> ```

Also had run tests for phoenix with https://github.com/apache/phoenix-thirdparty/pull/8#issuecomment-1832165125

**Comment by stoty** [comment]
No need, if you have tested with thirdparty-2.1 in both Omid and Phoenix at the same time, that's fine.

**Pull request merged**
