### PR TITLE
OMID-210 Use org.openlabtesting.protobuf:protoc:2.5.0 on Linux ARM64

### PR DESCRIPTION
**Pull request by martin-g**
Similar to https://github.com/apache/phoenix/pull/1238

### CODE REVIEW

**Comment by stoty** [comment]
OMID has its own JIRA project.
Please clone the Phoenix ticket to OMID, and update the patch description.

**Comment by stoty** [comment]
Sorry, wanted to close the Phoenix one.

**Comment by martin-g** [comment]
All done!

**Review by stoty — APPROVED** [review]
+1 LGTM

**Pull request closed without merging**
